version: '3'

services:
  weatherapp_backend:
    image: weatherapp_backend:latest
    container_name: weatherapp_backend
    ports:
      - "9000:9000"
    env_file:
      - ./backend.env
    networks:
      - network

  weatherapp_frontend:
    image: weatherapp_frontend:latest
    container_name: weatherapp_frontend
    ports:
      - "8000:8000"
    env_file:
      - frontend.env
    networks:
      - network

networks:
  network:
